FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /app
COPY backend/irkdoska /app/backend
WORKDIR /app/backend
RUN mvn -B clean package -DskipTests

FROM eclipse-temurin:21-jre

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/backend/target/irkdoska-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]

